程序开发过程是一个创造的过程，仅做对的事情远远不够。还需要考虑错的事情出现该怎么应对。

这符合老祖宗的经验，未虑胜，先虑败。

但对的事情是确定的，错的却无穷无尽。如何能够容错呢？

其实原则是什么呢？

你做了错的事，得到预想结果肯定不敢奢求，那怎样才是能够接受的呢？

最好这件事当没做过，我知道这样做不对，重新再来一次。

如何实现呢？

try{}catch(){}

那就是检测代码的异常，出现了，去寻找catch.

拥有catch代表我们对这个异常是有应对方案的，不用停止程序。按照应对方案解决就好。

如果没有catch，代表我们没预料到，这时候让程序直接终止，减少影响。

非正常情况有两种：异常（Exception）和错误（Error）

###### finally

异常机制有个漏洞，没有回收物理资源（数据库连接，网络连接，）的功能

因此，就有了finally块，位于所有代码之后，显示执行，除非前面调用了退出虚拟机的方法，不然怎样都会执行finally代码



